spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    master:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: jdbc:mysql://localhost:3506/db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
    slave:
      driver-class-name: ${spring.datasource.driver-class-name}
      url: jdbc:mysql://localhost:3516/db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
